# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regs',
            name='adate',
            field=models.DateField(blank=True, verbose_name='arrival date'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='allergy',
            field=models.CharField(blank=True, max_length=100, verbose_name='list allergies'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='ddate',
            field=models.DateField(blank=True, verbose_name='departure date'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='fname',
            field=models.CharField(max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='glutenallergy',
            field=models.BooleanField(verbose_name='gluten allergy'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='glutenfree',
            field=models.BooleanField(verbose_name='gluten free'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='lname',
            field=models.CharField(max_length=20, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='nsfnum',
            field=models.CharField(max_length=20, verbose_name='nsf number'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='other',
            field=models.CharField(blank=True, max_length=100, verbose_name='other relevant info'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='parkathotel',
            field=models.BooleanField(verbose_name='park at the hotel'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='program',
            field=models.CharField(choices=[('si2', 'SI2'), ('eager', 'EAGER'), ('rapid', 'RAPID'), ('voss', 'VOSS'), ('career', 'CAREER')], default='si2', max_length=6),
        ),
        migrations.AlterField(
            model_name='regs',
            name='ptitle',
            field=models.CharField(max_length=100, verbose_name='program title'),
        ),
    ]
