# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20161213_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regs',
            name='glutenallergy',
            field=models.BooleanField(verbose_name='gluten allergy'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='glutenfree',
            field=models.BooleanField(verbose_name='gluten free'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='other',
            field=models.CharField(blank=True, max_length=100, verbose_name='other relevant info'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='parkathotel',
            field=models.BooleanField(verbose_name='park at the hotel'),
        ),
    ]
