# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20161213_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regs',
            name='id',
        ),
        migrations.AlterField(
            model_name='regs',
            name='auth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
